apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtg-card-sync
  namespace: mtg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtg-card-sync
  template:
    metadata:
      labels:
        app: mtg-card-sync
    spec:
      containers:
      - name: mtg-card-sync
        image: harbor.home.virtualelephant.com/ve-lab/mtg-publisher:latest
        imagePullPolicy: Always
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq.signalwave.svc.cluster.local"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: username
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: password
        - name: RABBITMQ_QUEUE
          value: "mtgcards"
        - name: MESSAGE_RATE
          value: "1.0"
      restartPolicy: Always
