---
apiVersion: v1
kind: Namespace
metadata:
  name: mtg
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: mtg
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi
  storageClassName: standard-retain
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mtg
type: Opaque
data:
  POSTGRES_USER: ZGVwbG95 # Base64-encoded 'deploy'
  POSTGRES_PASSWORD: Vk13YXJlMTIzIQ== # Base64-encoded 'VMware123!'
  POSTGRES_DB: bXRnX2RhdGFiYXNl # Base64-encoded 'mtg_database'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: mtg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: harbor.home.virtualelephant.com/ve-lab/postgres-mtg:latest
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: mtg
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
