apiVersion: batch/v1
kind: Job
metadata:
  name: init-mtg-db
  namespace: mtg
spec:
  template:
    spec:
      containers:
        - name: init-db
          image: harbor.home.virtualelephant.com/ve-lab/postgres-mtg:latest
          command: ["psql"]
          args:
            - "--host=postgres"
            - "--username=$(POSTGRES_USER)"
            - "--dbname=$(POSTGRES_DB)"
            - "--file=/docker-entrypoint-initdb.d/mtg_schema.sql"
          envFrom:
            - secretRef:
                name: postgres-secret
      restartPolicy: OnFailure