apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: mtg
type: Opaque
data:
  username: ZGVwbG95  # Base64-encoded 'deploy'
  password: Vk13YXJlMTIzIQ==  # Base64-encoded 'VMware123!'
